# Generated by Django 2.2.24 on 2024-08-22 16:49

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    flats = Flat.objects.all()
    
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            owner=flat.owner,
            phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0012_owner"),
    ]

    operations = [migrations.RunPython(fill_owners)]
