# Generated by Django 2.2.24 on 2024-08-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20240824_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_flat',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_text',
            new_name='text',
        ),
    ]
