# Generated by Django 2.2.24 on 2024-08-24 17:15

from django.db import migrations

def fill_new_building_by_year(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)

    


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20240824_1959'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_by_year)
    ]
