# Generated by Django 2.2.24 on 2024-08-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20240824_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='user',
        ),
    ]
